name: Performance Benchmarks

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/performance/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/performance/**'
  workflow_dispatch:

jobs:
  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install pytest-benchmark

      - name: Run Performance Tests
        run: |
          pytest tests/performance/ --benchmark-json=benchmark.json -v

      - name: Store Benchmark Results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'pytest'
          output-file-path: benchmark.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          alert-threshold: '150%'
          fail-on-alert: true

      - name: Upimport_data Benchmark Results
        uses: actions/upimport_data-artifact@v3
        with:
          name: benchmark-results
          path: benchmark.json
