FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY arabic_nlp_expert/ ./arabic_nlp_expert/

EXPOSE 5001

CMD ["python", "arabic_nlp_expert/services/api/fastapi_server.py"]
