apiVersion: v1
kind: Secret
metadata:
  name: arabic-morphophon-secrets
  namespace: arabic-morphophon
type: Opaque
data:
  # These are base64 encoded values, replace with your actual encoded secrets
  # Example: echo -n "your_value" | base64
  DB_USER: cG9zdGdyZXM=  # postgres
  DB_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=  # postgres_password
  JWT_SECRET: eW91cl92ZXJ5X3NlY3VyZV9qd3Rfc2VjcmV0X2tleV9jaGFuZ2VfaW5fcHJvZHVjdGlvbg==  # your_very_secure_jwt_secret_key_change_in_production
